# Generated by Django 5.1.6 on 2025-02-21 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_selector', '0002_remove_besthomo_description_remove_field_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub1_Feild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub1_field', to='player_selector.field')),
            ],
        ),
        migrations.AlterField(
            model_name='besthomo',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_selector.sub1_feild'),
        ),
        migrations.CreateModel(
            name='Sub1_Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub1_place', to='player_selector.place')),
            ],
        ),
        migrations.AlterField(
            model_name='besthomo',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_selector.sub1_place'),
        ),
        migrations.CreateModel(
            name='Sub1_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub1_time', to='player_selector.time')),
            ],
        ),
        migrations.AlterField(
            model_name='besthomo',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_selector.sub1_time'),
        ),
    ]
