# Generated by Django 5.1.6 on 2025-02-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_selector', '0003_sub1_feild_alter_besthomo_field_sub1_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='besthomo',
            name='field',
        ),
        migrations.RemoveField(
            model_name='besthomo',
            name='place',
        ),
        migrations.RemoveField(
            model_name='besthomo',
            name='time',
        ),
        migrations.AddField(
            model_name='besthomo',
            name='field',
            field=models.ManyToManyField(to='player_selector.sub1_feild'),
        ),
        migrations.AddField(
            model_name='besthomo',
            name='place',
            field=models.ManyToManyField(to='player_selector.sub1_place'),
        ),
        migrations.AddField(
            model_name='besthomo',
            name='time',
            field=models.ManyToManyField(to='player_selector.sub1_time'),
        ),
    ]
