# Generated by Django 5.1.6 on 2025-02-21 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_selector', '0004_remove_besthomo_field_remove_besthomo_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='besthomo',
            name='field',
        ),
        migrations.RemoveField(
            model_name='besthomo',
            name='place',
        ),
        migrations.RemoveField(
            model_name='besthomo',
            name='time',
        ),
        migrations.AddField(
            model_name='besthomo',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='player_selector.sub1_feild'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='besthomo',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='player_selector.sub1_place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='besthomo',
            name='time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='player_selector.sub1_time'),
            preserve_default=False,
        ),
    ]
