# Generated by Django 5.1.6 on 2025-02-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_selector', '0005_remove_besthomo_field_remove_besthomo_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub1_feild',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub1_place',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub1_time',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
