# Generated by Django 5.1.6 on 2025-02-21 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_selector', '0006_sub1_feild_name_sub1_place_name_sub1_time_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BestHomo',
            new_name='BestHomo1',
        ),
        migrations.AlterField(
            model_name='besthomo1',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_selector.field'),
        ),
        migrations.AlterField(
            model_name='besthomo1',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_selector.place'),
        ),
        migrations.AlterField(
            model_name='besthomo1',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_selector.time'),
        ),
        migrations.CreateModel(
            name='Sub1_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sub1f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub1_field', to='player_selector.field')),
            ],
        ),
        migrations.CreateModel(
            name='BestHomo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_selector.sub1_place')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_selector.sub1_time')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_selector.sub1_field')),
            ],
        ),
        migrations.DeleteModel(
            name='Sub1_Feild',
        ),
    ]
