# Generated by Django 5.1.6 on 2025-02-21 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_selector', '0007_rename_besthomo_besthomo1_alter_besthomo1_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub1_field',
            name='sub1f',
        ),
        migrations.RemoveField(
            model_name='sub1_place',
            name='sub1p',
        ),
        migrations.RemoveField(
            model_name='sub1_time',
            name='sub1t',
        ),
        migrations.AddField(
            model_name='field',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_fields', to='player_selector.field'),
        ),
        migrations.AddField(
            model_name='field',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_places', to='player_selector.place'),
        ),
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='time',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_times', to='player_selector.time'),
        ),
        migrations.AddField(
            model_name='time',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='time',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='BestHomo2',
        ),
        migrations.DeleteModel(
            name='Sub1_Field',
        ),
        migrations.DeleteModel(
            name='Sub1_Place',
        ),
        migrations.DeleteModel(
            name='Sub1_Time',
        ),
    ]
