# Generated by Django 5.1.6 on 2025-03-18 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_selector', '0008_remove_sub1_field_sub1f_remove_sub1_place_sub1p_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='place',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='time',
            name='slug',
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='field',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='player_selector.field'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='player_selector.place'),
        ),
        migrations.AlterField(
            model_name='time',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='time',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='player_selector.time'),
        ),
        migrations.CreateModel(
            name='BestHomo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field', models.ManyToManyField(to='player_selector.field')),
                ('place', models.ManyToManyField(to='player_selector.place')),
                ('time', models.ManyToManyField(to='player_selector.time')),
            ],
        ),
        migrations.AlterField(
            model_name='vote',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_selector.besthomo'),
        ),
        migrations.DeleteModel(
            name='BestHomo1',
        ),
    ]
